web:
  build:
    context: ../hawana-hse-web-admin
    dockerfile: Dockerfile

  image: hawana-hse-web-admin:latest
  container_name: hawana-web
  restart: unless-stopped

  depends_on:
    - core

  ports:
    - "3005:3000"

  environment:
    NODE_ENV: production
    NEXT_PUBLIC_API_BASE_URL: http://localhost:3005/api
    NEXT_PUBLIC_API_PREFIX: /v1
    CORE_API_BASE_URL: http://hawana-core:3001
    APP_BASE_URL: http://web:3000